use serde::Serialize;
use clap::Parser;
use rayon::prelude::*;
use regex::Regex;
// use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;
use polars::prelude::{DataFrame, NamedFrom, Series};
use anyhow::{anyhow, Result};

/// A command‑line tool that processes verilog netlists and associated ATPG/fault files to
/// build a CSV dataset.  This is a Rust re‑implementation of a Python script used for
/// random circuit generation.  The tool scans a directory for verilog files, extracts
/// gate definitions, patterns, faults and ATPG summaries, and writes a single CSV file.
#[derive(Parser, Debug)]
#[command(name = "rust_data_preprocessing")]
#[command(author = "Generated by ChatGPT")]
#[command(about = "Process verilog circuits into a CSV dataset", long_about = None)]
struct Args {
    /// Path to the directory containing the verilog netlists.
    #[arg(short = 'c', long = "circuit_folder", value_name = "DIR", required = true)]
    circuit_folder: PathBuf,

    /// Path to the directory containing extracted ATPG/fault files.  Each
    /// subdirectory should correspond to a verilog module name and contain
    /// atpg.txt, faults.txt and patterns.txt.
    #[arg(short = 'o', long = "output_folder", value_name = "DIR", required = true)]
    output_folder: PathBuf,

    /// Destination CSV file where the aggregated dataset will be written.
    #[arg(short = 'd', long = "out_data_file", value_name = "FILE", required = true)]
    out_data_file: PathBuf,

    /// Number of worker threads to use.  Defaults to the number of CPUs.
    #[arg(short = 'p', long = "cpu_pool", value_name = "N", default_value_t = num_cpus::get())]
    cpu_pool: usize,
}

/// Structure holding the extracted fields for a single module.  This mirrors
/// the Python output and includes counts of instances, wires, inputs and
/// outputs.
#[derive(Serialize)]
struct ModuleRecord {
    module_name: String,
    netlist_only_gates: String,
    patterns: String,
    faults: String,
    atpg: String,
    netlist: String,
    num_instances: usize,
    num_wires: usize,
    num_inputs: usize,
    num_outputs: usize,
}

fn main() -> Result<()> {
    let args = Args::parse();

    // Compile regular expressions up front.  These correspond to the regexes
    // used in the Python implementation.  We compile patterns for tokenising
    // binary digits, collapsing whitespace, matching instances, and parsing
    // declarations and signal names.
    let regex_pattern_extraction = Regex::new(r"force_all_pis\s*=\s*([01\s]+)Time\s+\d+:\s+measure_all_pos\s*=\s*([01\s]+)")?;
    let regex_remove_multi_wspaces = Regex::new("\\s+")?;
    let regex_instances = Regex::new(r"\w+\s+\w+\s*\(")?;
    // Regex to capture full declarations like `input [15:0] a, b[0:7];`
    let decl_re = Regex::new(
        r"(?m)^\s*(?P<kind>input|output|inout|wire|reg)\b\s*(?P<packed>\[\s*\d+\s*:\s*\d+\s*\])?\s*(?P<rest>[^;]+);",
    )?;
    // Regex to capture each signal declarator name and its unpacked dimension
    let name_re = Regex::new(
        r"(?m)^\s*(?P<name>[A-Za-z_]\w*)\s*(?P<unpacked>\[\s*\d+\s*:\s*\d+\s*\])?\s*$",
    )?;

    // Walk the input folder and collect all verilog files.
    let verilog_files = list_files(&args.circuit_folder)?;

    // Prepare writer for the output CSV.  We wrap it in a Mutex so that
    // multiple threads can safely write to it.
    let wtr = std::sync::Mutex::new(csv::Writer::from_path(&args.out_data_file)?);

    // Configure rayon thread pool size if the user passed a specific value.
    let pool = rayon::ThreadPoolBuilder::new().num_threads(args.cpu_pool).build()?;
    pool.install(|| {
        verilog_files.par_iter().for_each(|verilog_file| {
            // Process each verilog file to extract its associated data.
            match process_verilog_file(
                verilog_file,
                &args.output_folder,
                &regex_pattern_extraction,
                &regex_remove_multi_wspaces,
                &regex_instances,
                &decl_re,
                &name_re,
            ) {
                Ok(record) => {
                    // Acquire writer lock and serialize record into CSV.
                    if let Ok(mut writer) = wtr.lock() {
                        if let Err(err) = writer.serialize(record) {
                            eprintln!("Failed to write CSV row for {:?}: {}", verilog_file, err);
                        }
                    }
                }
                Err(err) => eprintln!("Failed to process {:?}: {}", verilog_file, err),
            }
        });
    });

    // Flush remaining data to disk.
    wtr.lock().unwrap().flush()?;
    Ok(())
}

/// Recursively list all files in the given directory.  Only files (not
/// directories) are returned.  An error will be propagated if the folder
/// cannot be read.
fn list_files(directory: &Path) -> Result<Vec<PathBuf>> {
    if !directory.exists() || !directory.is_dir() {
        return Err(anyhow!("Input directory {:?} does not exist or is not a directory", directory));
    }
    let mut files = Vec::new();
    for entry in WalkDir::new(directory).into_iter().filter_map(|e| e.ok()) {
        if entry.file_type().is_file() {
            files.push(entry.into_path());
        }
    }
    Ok(files)
}

/// Process a single verilog file.  This function extracts the module name,
/// netlist definition and gate list from the verilog file itself, and then
/// loads the corresponding atpg, faults and patterns data from the supplied
/// output folder.  Regular expressions are passed in for tokenizing binary
/// digits and stripping duplicate whitespace.
fn process_verilog_file(
    verilog_path: &PathBuf,
    output_folder: &PathBuf,
    regex_pattern_extraction: &Regex,
    regex_remove_multi_wspaces: &Regex,
    regex_instances: &Regex,
    decl_re: &Regex,
    name_re: &Regex,
) -> Result<ModuleRecord> {
    // Determine module name by stripping the file extension.  The Python
    // implementation splits on '_' and uses the second part as the name; here
    // we split on '_' and use the second segment if possible to match the
    // Python implementation.
    let full_stem = verilog_path
        .file_stem()
        .unwrap_or_default()
        .to_string_lossy()
        .to_string();
    let mut module_name = full_stem.clone();
    if let Some((_, second)) = full_stem.split_once('_') {
        module_name = second.to_string();
    }
    let module_dir = output_folder.join(&module_name);

    // Read verilog source and build netlist strings.  Comments (both block and
    // line), blank lines and lines containing only stars are filtered out.
    let verilog_content = fs::read_to_string(verilog_path).unwrap_or_default();
    let verilog_text = verilog_content.clone();
    let mut netlist_lines = Vec::new();
    let mut netlist_only_gates_lines = Vec::new();
    for line in verilog_content.lines() {
        // Skip block comments, any line with '*' (to match Python logic),
        // whitespace‑only lines and single line comments
        if line.contains("/*")
            || line.contains('*')
            || line.trim().is_empty()
            || line.trim_start().starts_with("//")
        {
            continue;
        }
        let line_strip = line.trim();
        netlist_lines.push(line_strip.to_string());
        // Exclude wire/input/output declarations from the gate list
        if !line_strip.starts_with("wire")
            && !line_strip.starts_with("input")
            && !line_strip.starts_with("output")
        {
            netlist_only_gates_lines.push(line_strip.to_string());
        }
    }
    let netlist = netlist_lines.join("\n");
    let netlist_only_gates = netlist_only_gates_lines.join("\n");

    // Compute number of instance lines: lines that match the instance regex and
    // do not contain the keyword 'module'.
    let num_instances = netlist_lines
        .iter()
        .filter(|line| !line.contains("module") && regex_instances.is_match(line))
        .count();
    // Count the number of bits declared for wires, inputs and outputs
    let num_wires = count_bits_for_keyword(&verilog_text, "wire", decl_re, name_re);
    let num_inputs = count_bits_for_keyword(&verilog_text, "input", decl_re, name_re);
    let num_outputs = count_bits_for_keyword(&verilog_text, "output", decl_re, name_re);

    // --- Read ATPG summary ---
    let atpg_path = module_dir.join("atpg.txt");
    let mut atpg_lines = Vec::<String>::new();
    if atpg_path.exists() {
        if let Ok(file_data) = fs::read_to_string(&atpg_path) {
            let mut flag = false;
            for raw_line in file_data.lines() {
                // Collapse multiple whitespace and trim
                let line = regex_remove_multi_wspaces.replace_all(raw_line.trim(), " ");
                let line_str = line.to_string();
                if line_str.contains("Summary Report") {
                    flag = true;
                } else if flag && !line_str.contains("---") && !line_str.is_empty() {
                    atpg_lines.push(line_str);
                }
            }
        }
    }
    let atpg = atpg_lines.join("\n");

    // --- Read Faults ---
    let faults_path = module_dir.join("faults.txt");
    let mut faults = String::new();
    if faults_path.exists() {
        if let Ok(file_data) = fs::read_to_string(&faults_path) {
            let mut lines_processed = Vec::new();
            for line in file_data.lines() {
                let trimmed = line.trim();
                if trimmed.is_empty() {
                    continue;
                }
                // Split on whitespace and rejoin with single spaces, similar to
                // pandas.read_csv(..., sep='\s+', header=None).apply(' '.join)
                let parts: Vec<&str> = trimmed.split_whitespace().collect();
                lines_processed.push(parts.join(" "));
            }
            faults = lines_processed.join("\n");
        }
    }

    // --- Read Patterns ---
    let patterns_path = module_dir.join("patterns.txt");
    let mut patterns = String::new();
    if patterns_path.exists() {
        if let Ok(file_data) = fs::read_to_string(&patterns_path) {
            let mut pairs: Vec<(String, String)> = Vec::new();
            for caps in regex_pattern_extraction.captures_iter(&file_data) {
                let pi_block = caps.get(1).map_or("", |m| m.as_str());
                let po_block = caps.get(2).map_or("", |m| m.as_str());
                // Remove all whitespace
                let pi: String = pi_block.chars().filter(|c| !c.is_whitespace()).collect();
                let po: String = po_block.chars().filter(|c| !c.is_whitespace()).collect();
                pairs.push((pi, po));
            }

            // Build a DataFrame using Polars to pretty print like pandas
            if !pairs.is_empty() {
                // Split the pairs into two separate vectors
                let col0: Vec<String> = pairs.iter().map(|p| p.0.clone()).collect();
                let col1: Vec<String> = pairs.iter().map(|p| p.1.clone()).collect();
                let df = DataFrame::new(vec![
                    Series::new("0", col0),
                    Series::new("1", col1),
                ])?;
                // The Display implementation for DataFrame produces a readable table
                patterns = format!("{df}");
            }
        }
    }

    Ok(ModuleRecord {
        module_name,
        netlist_only_gates,
        patterns,
        faults,
        atpg,
        netlist,
        num_instances,
        num_wires,
        num_inputs,
        num_outputs,
    })
}

/// Convert a Verilog range expression like `[msb:lsb]` into an integer width.
/// If `rng` is `None`, the width defaults to 1.  The expression may be either
/// ascending or descending; the result is `abs(msb - lsb) + 1`.
fn parse_range(rng: Option<&str>) -> usize {
    if let Some(range_str) = rng {
        // Extract all numbers in the range.  We ignore non‑digit characters.
        let digit_re = Regex::new(r"\d+").unwrap();
        let numbers: Vec<isize> = digit_re
            .find_iter(range_str)
            .filter_map(|m| m.as_str().parse::<isize>().ok())
            .collect();
        if numbers.len() >= 2 {
            let msb = numbers[0];
            let lsb = numbers[1];
            return ((msb - lsb).abs() as usize) + 1;
        }
    }
    1
}

/// Count the total number of bits declared for a given keyword (e.g., input,
/// output or wire) in a Verilog text.  This mirrors the Python function
/// `count_bits_for_keyword`.  It iterates over all declaration matches and
/// multiplies the packed bus width by the unpacked array length for each
/// declarator.
fn count_bits_for_keyword(
    verilog_text: &str,
    keyword: &str,
    decl_re: &Regex,
    name_re: &Regex,
) -> usize {
    let mut total_bits = 0usize;
    for cap in decl_re.captures_iter(verilog_text) {
        let kind = cap.name("kind").map(|m| m.as_str()).unwrap_or("");
        if kind != keyword {
            continue;
        }
        let packed = cap.name("packed").map(|m| m.as_str());
        let rest = cap.name("rest").map(|m| m.as_str()).unwrap_or("");
        let bus_width = parse_range(packed);
        for token in rest.split(',') {
            let token = token.trim();
            if let Some(nm) = name_re.captures(token) {
                let unpacked = nm.name("unpacked").map(|m| m.as_str());
                let array_len = parse_range(unpacked);
                total_bits += bus_width * array_len;
            }
        }
    }
    total_bits
}