# One externally supplied combinational pattern. No ATPG or Python simulation.
# REQUEST_FILE is generated by tetramax_backend.py using hex-encoded Tcl words.
proc canonical {name} {
    if {[string index $name 0] eq "/"} { set name [string range $name 1 end] }
    if {[string index $name 0] eq "\\"} { set name [string range $name 1 end] }
    return [string trim $name]
}
proc value_pair {data} {
    set data [string toupper [string trim $data]]
    if {![regexp {^([01XZ])(?:/([01XZ]))?$} $data all good bad]} {
        error "Unsupported combinational pin data: $data"
    }
    if {$bad eq ""} { set bad $good }
    return [list $good $bad]
}
proc register_driver {map_name net path} {
    upvar 1 $map_name drivers
    if {$net eq ""} { return }
    if {[dict exists $drivers $net] && [dict get $drivers $net] ne $path} {
        error "Multiple native drivers for net $net"
    }
    dict set drivers $net $path
}
proc export_values {file_name} {
    set f [open $file_name w]
    foreach_in_collection pin [get_pins] {
        set net [canonical [get_attribute $pin net_name]]
        set path [get_attribute $pin pin_pathname]
        set type [get_attribute [get_attribute $pin gate] cell_type]
        if {$type eq "PI" || $type eq "PO"} { set net [canonical $path] }
        if {$net eq "" || [get_attribute $pin direction] ne "OUT"} { continue }
        set pair [value_pair [get_attribute $pin pin_data]]
        puts $f "$net\t[lindex $pair 0]\t[lindex $pair 1]"
    }
    close $f
}
if {[catch {
    source $env(REQUEST_FILE)
    set_netlist -nosequential_modeling
    foreach lib $cell_libraries { read_netlist $lib -library }
    read_netlist $verilog_file
    set_build -nonet_connections_change_netlist -nodelete_unused_gates
    run_build_model $top_module
    foreach_in_collection cell [get_cells -all] {
        set kind [get_attribute $cell cell_type]
        if {$kind in {DFF DLAT MEMORY PIO}} { error "Unsupported design primitive: $kind" }
    }
    run_drc $stil_file
    set_patterns -delete
    set_patterns -external $stil_file -sensitive
    # Map a net stem to its unique native driver, never to a sink branch.
    set drivers [dict create]
    set gate_drivers [dict create]
    set pins [dict create]
    foreach_in_collection pin [get_pins] {
        set path [get_attribute $pin pin_pathname]
        dict set pins [canonical $path] $path
        set gate [get_attribute $pin gate]
        set kind [get_attribute $gate cell_type]
        if {[get_attribute $pin direction] ne "OUT" || $kind eq "PO"} { continue }
        register_driver gate_drivers [get_attribute $gate cell_id] $path
        set net [canonical [get_attribute $pin net_name]]
        register_driver drivers $net $path
        if {$kind eq "PI"} {
            register_driver drivers [canonical $path] $path
        }
    }
    # A direct assign can give a PO a different name from its native net
    # (e.g. assign gray_decode[7] = gray[7]). Resolve through native connectivity
    # to the stem driver; injecting on the PO would only fault that branch.
    foreach_in_collection pin [get_pins] {
        set gate [get_attribute $pin gate]
        set kind [get_attribute $gate cell_type]
        if {$kind ne "PO"} { continue }
        # PI/PO primitives have empty net_name in O-2018.06. Use the PO's
        # immediate native fanin, not transitive PI fanin or a guessed net name.
        set sources [get_attribute $gate fanin_gates]
        if {[sizeof_collection $sources] != 1} {
            error "Expected one native driver for output [get_attribute $pin pin_pathname]"
        }
        foreach_in_collection source $sources {
            set source_id [get_attribute $source cell_id]
            # A PI cell's `pins` collection can be empty even though get_pins
            # exposes its output. Use the output indexed in the first pass.
            if {[dict exists $gate_drivers $source_id]} {
                register_driver drivers [canonical [get_attribute $pin pin_pathname]] [dict get $gate_drivers $source_id]
            }
        }
    }
    set target [canonical $fault_net]
    if {$fault_kind eq "pin" && [dict exists $pins $target]} {
        set fault_pin [dict get $pins $target]
    } elseif {$fault_kind eq "net" && [dict exists $drivers $target]} {
        set fault_pin [dict get $drivers $target]
    } else { error "No unique native driver for requested $fault_kind fault $fault_net" }
    set_faults -model stuck -report uncollapsed
    remove_faults -all
    add_faults $fault_pin -stuck $stuck_at
    if {[sizeof_collection [get_faults -all]] != 1} { error "Expected exactly one target fault" }
    # Pin-data resimulation ignores the model's claimed output values. It also
    # provides good outputs used to replace the initial H observation placeholders.
    set_pindata -fault_sim_results [list $fault_pin $stuck_at 0]
    export_values pre_values.tsv
    set good_outputs [dict create]
    set f [open pre_values.tsv r]
    foreach line [split [read $f] "\n"] {
        if {$line eq ""} { continue }
        set row [split $line "\t"]
        dict set good_outputs [lindex $row 0] [lindex $row 1]
    }
    close $f
    set measures ""
    foreach po $po_names {
        set value [dict get $good_outputs [canonical $po]]
        append measures [string map {0 L 1 H Z T} $value]
    }
    set f [open $stil_file r]; set stil [read $f]; close $f
    set old "\"_po\"=[string repeat H [llength $po_names]]; \}"
    set new "\"_po\"=$measures; \}"
    if {[string first $old $stil] < 0} { error "Missing output measure placeholder" }
    set f [open graded.stil w]; puts -nonewline $f [string map [list $old $new] $stil]; close $f
    set_patterns -external graded.stil -sensitive
    run_simulation > good_simulation.log
    run_fault_sim -ndetects 1 > fault_simulation.log
    report_faults -all -uncollapsed > faults.tsv
    set_pindata -fault_sim_results [list $fault_pin $stuck_at 0]
    export_values values.tsv
    set f [open result.tsv w]
    puts $f "fault_pin\t$fault_pin"
    foreach_in_collection fault [get_faults -all] {
        puts $f "fault_status\t[get_attribute $fault class_behavior]"
    }
    puts $f "complete\t$request_id"
    close $f
    report_licenses -quantity > licenses.log
} message]} {
    puts stderr "TMAX_REQUEST_ERROR: $message"
    set f [open error.txt w]; puts $f $message; close $f
    exit 1
}
quit
